// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pubsub.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Pubsub {
  public static partial class PubSub
  {
    static readonly string __ServiceName = "pubsub.PubSub";

    static readonly grpc::Marshaller<global::Pubsub.Subscription> __Marshaller_Subscription = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Pubsub.Subscription.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Pubsub.Event> __Marshaller_Event = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Pubsub.Event.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Pubsub.Unsubscription> __Marshaller_Unsubscription = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Pubsub.Unsubscription.Parser.ParseFrom);

    static readonly grpc::Method<global::Pubsub.Subscription, global::Pubsub.Event> __Method_Subscribe = new grpc::Method<global::Pubsub.Subscription, global::Pubsub.Event>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Subscribe",
        __Marshaller_Subscription,
        __Marshaller_Event);

    static readonly grpc::Method<global::Pubsub.Subscription, global::Pubsub.Unsubscription> __Method_Unsubscribe = new grpc::Method<global::Pubsub.Subscription, global::Pubsub.Unsubscription>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Unsubscribe",
        __Marshaller_Subscription,
        __Marshaller_Unsubscription);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Pubsub.PubsubReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PubSub</summary>
    public abstract partial class PubSubBase
    {
      public virtual global::System.Threading.Tasks.Task Subscribe(global::Pubsub.Subscription request, grpc::IServerStreamWriter<global::Pubsub.Event> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Pubsub.Unsubscription> Unsubscribe(global::Pubsub.Subscription request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PubSub</summary>
    public partial class PubSubClient : grpc::ClientBase<PubSubClient>
    {
      /// <summary>Creates a new client for PubSub</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PubSubClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PubSub that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PubSubClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PubSubClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PubSubClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Pubsub.Event> Subscribe(global::Pubsub.Subscription request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Subscribe(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Pubsub.Event> Subscribe(global::Pubsub.Subscription request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Subscribe, null, options, request);
      }
      public virtual global::Pubsub.Unsubscription Unsubscribe(global::Pubsub.Subscription request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Unsubscribe(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Pubsub.Unsubscription Unsubscribe(global::Pubsub.Subscription request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Unsubscribe, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Pubsub.Unsubscription> UnsubscribeAsync(global::Pubsub.Subscription request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UnsubscribeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Pubsub.Unsubscription> UnsubscribeAsync(global::Pubsub.Subscription request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Unsubscribe, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PubSubClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PubSubClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PubSubBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Subscribe, serviceImpl.Subscribe)
          .AddMethod(__Method_Unsubscribe, serviceImpl.Unsubscribe).Build();
    }

  }
}
#endregion
